apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-Deployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: adarbe/final-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
