apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-phone-book
spec:
  selector:
    matchLabels:
      app: final-phone-book
  replicas: 3
  template:
    metadata:
      labels:
        app: final-phone-book
    spec:
      containers:
      - name: final-phone-book
        image: adarbe/final-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8181