node('linux') {
checkout scm
def dockerfile = "Dockerfile-app"
def app = ''
 
    stage('pull code') {
       git branch: 'master',
       url: "https://github.com/Adarbe/finalapp.git"
    }
       
    stage('Docker build ') {
     script {
      app = docker.build ("adarbe/final-project:${BUILD_NUMBER}", "-f ${dockerfile} https://github.com/Adarbe/finalapp.git")  
      }
    }
    
    stage('deployment'){
        script{
          docker.withRegistry("https://registry.hub.docker.com" ,"dockerhub.adarbe"){
          app.push()
        }
      }  
  }
    stage("deploy app") {
      withAWS(region: 'us-east-1'){
                sh "aws eks update-kubeconfig --name opsSchool-eks-final-project"
                sh "kubectl apply -f ${services.yaml} https://github.com/Adarbe/opsschool-final-project.git "
                sh "kubectl apply -f ${deployment.yaml} https://github.com/Adarbe/opsschool-final-project.git "
    }
  }
}
